#!/bin/bash

CXX = cc
MUIPATH =


CCFLAGS = -Wall -Wextra
CICODEPATH = -I../../
CIEIGENPATH = -I
CIMUIPATH = -I${MUIPATH}/wrappers/C -I${MUIPATH}
CLPATH = -L${MUIPATH} -L${MUIPATH}/wrappers/C
CLNAME = -lwrapperC 
LDFLAGS = -lstdc++


default: fixedRelaxation_CAPI.o aitken_CAPI.o iqnils_CAPI.o
	ar rcs libmuiCouplingMethodsCAPI.a fixedRelaxation_CAPI.o aitken_CAPI.o iqnils_CAPI.o

%.o : %.cpp
	${CXX} ${CCFLAGS} -c $^ -o $@ ${CICODEPATH} ${CIEIGENPATH} ${CIMUIPATH} ${CLPATH} ${CLNAME} ${LDFLAGS}

.PHONY : clean

clean :
	${RM} -rf *.o *.a
